RX interruption catched
TASK_ALLOCATION_SEND
Got slot: 0 
Task total size (txt+bss): 3556 
Task addr: 2147522956 
Task slot: 0 
Task slot TaskAddr: 2147522956 
RX interruption catched
TASK_ALLOCATION_FINISHED
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um TASK_START!
RX interruption catched
Chegou um TASK_RUN!
Starting Task 0  from app 1 
taskSlot run: 0 
Bank INIT
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send failed - NI_TX occupied!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send failed - NI_TX occupied!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
dynamicEnergy_Router >> 3953125 
total instructions~~~> 2006006 
TotalEnergy: 19224173 
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 992830 
TotalEnergy: 43381093 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1000001 
TotalEnergy: 43826653 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1004950 
TotalEnergy: 44177133 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 995153 
TotalEnergy: 43752358 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 999900 
TotalEnergy: 43977635 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1010707 
TotalEnergy: 44404687 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
dynamicEnergy_Router >> 3953125 
total instructions~~~> 990709 
TotalEnergy: 43588017 
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1002122 
TotalEnergy: 44062282 
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 996365 
TotalEnergy: 43508239 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1000102 
TotalEnergy: 43829937 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1000001 
TotalEnergy: 43943892 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 999799 
TotalEnergy: 43975266 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1009697 
TotalEnergy: 44365745 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 995961 
TotalEnergy: 43823013 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 994446 
TotalEnergy: 43723256 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1001415 
TotalEnergy: 44009727 
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 998380 
TotalEnergy: 43906901 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 7 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 0 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 1 
API_Try2Send success!
dynamicEnergy_Router >> 3953125 
total instructions~~~> 1000102 
TotalEnergy: 43955674 
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 2 
from app: 1 
TX interruption catched
API_Try2Send failed - empty SendQueue!
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 2 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 2  in the PIPE slot 3 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 3 
Mensagem encontrada no pipe!
SendingQueue_front: 3 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 3  in the PIPE slot 1 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 4 
Mensagem encontrada no pipe!
SendingQueue_front: 4 
API_Try2Send success!
TX interruption catched
API_Try2Send failed - empty SendQueue!
taskSlot: 0 
Adding a msg to task 4  in the PIPE slot 0 
from app: 1 
RX interruption catched
Chegou um message request! App: 1 Task: 2 
Mensagem encontrada no pipe!
SendingQueue_front: 5 
API_Try2Send success!
RX interruption catched
Chegou um message request! App: 1 Task: 1 
Mensagem encontrada no pipe!
SendingQueue_front: 6 
API_Try2Send failed - NI_TX occupied!
TX interruption catched
API_Try2Send success!
taskSlot: 0 
Adding a msg to task 1  in the PIPE slot 3 
from app: 1 
dynamicEnergy_Router >> 3953125 
total instructions~~~> 999799 
TotalEnergy: 43631984 
